- name: testing variable precedence
  hosts: all
  vars:
    NAME: sivakumar-play
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter trainer name
    private: false
  tasks:
  - name: variable at task level
    vars:
      NAME: sivakumar-task
    ansible.builtin.debug:
      msg: "Trainer name is {{NAME}}"